import React, { useState } from 'react';

/**
 * RegistrationSuccess - Displays registration success and credentials
 * Follows Single Responsibility Principle
 */
const RegistrationSuccess = ({ successData, onClose }) => {
  const [copied, setCopied] = useState(false);

  const handleCopyPassword = () => {
    if (successData?.patientData?.temporaryPassword) {
      navigator.clipboard.writeText(successData.patientData.temporaryPassword)
        .then(() => {
          setCopied(true);
          setTimeout(() => setCopied(false), 2000);
        })
        .catch(() => {
          alert('Failed to copy password. Please copy it manually.');
        });
    }
  };

  const handlePrintCredentials = () => {
    const { patient, healthCard, temporaryPassword } = successData.patientData;
    
    const printWindow = window.open('', '', 'width=600,height=400');
    printWindow.document.write(`
      <html>
        <head>
          <title>Patient Credentials - ${patient.name}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 20px; }
            .header { text-align: center; margin-bottom: 30px; }
            .info { margin: 10px 0; }
            .password { font-size: 18px; font-weight: bold; background: #ffffcc; padding: 10px; border: 2px dashed #333; }
            .warning { color: red; margin-top: 20px; font-weight: bold; }
          </style>
        </head>
        <body>
          <div class="header">
            <h2>Smart Healthcare System</h2>
            <h3>Patient Registration Credentials</h3>
          </div>
          <div class="info"><strong>Patient Name:</strong> ${patient.name}</div>
          <div class="info"><strong>Patient ID:</strong> ${patient._id}</div>
          <div class="info"><strong>Health Card ID:</strong> ${healthCard.cardID}</div>
          <div class="info"><strong>Email:</strong> ${patient.email}</div>
          <br/>
          <div class="password">
            <strong>Temporary Password:</strong> ${temporaryPassword}
          </div>
          <div class="warning">
            ⚠️ IMPORTANT: This is a temporary password. The patient must change it upon first login.
          </div>
          <div style="margin-top: 30px; font-size: 12px; color: #666;">
            <p>Generated on: ${new Date().toLocaleString()}</p>
            <p>Generated by: Staff Member</p>
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
  };

  const { patient, healthCard, temporaryPassword } = successData.patientData;

  return (
    <div className="bg-white rounded-lg shadow-lg p-8">
      <div className="text-center">
        <SuccessIcon />
        <h3 className="text-2xl font-bold text-gray-900 mb-2">{successData.message}</h3>
        
        <PatientInfo patient={patient} healthCard={healthCard} />
        
        <PasswordDisplay
          password={temporaryPassword}
          onCopy={handleCopyPassword}
          onPrint={handlePrintCredentials}
          copied={copied}
        />

        <EmailConfirmation />

        <button
          onClick={onClose}
          className="w-full mt-8 bg-green-600 text-white py-3 px-6 rounded-lg hover:bg-green-700 font-bold text-lg transition-colors"
        >
          Done - Return to Dashboard
        </button>

        <p className="mt-4 text-xs text-gray-500">
          Please ensure you have saved or provided the password to the patient before closing this window.
        </p>
      </div>
    </div>
  );
};

// Sub-components (following ISP - Interface Segregation)
const SuccessIcon = () => (
  <div className="mx-auto flex items-center justify-center h-16 w-16 rounded-full bg-green-100 mb-4">
    <svg className="h-8 w-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path>
    </svg>
  </div>
);

const PatientInfo = ({ patient, healthCard }) => (
  <div className="mt-6 bg-blue-50 p-6 rounded-lg border-2 border-blue-200">
    <h4 className="font-semibold text-blue-900 mb-4 text-lg">Patient Information</h4>
    <div className="text-left space-y-3 text-sm">
      <div className="grid grid-cols-2 gap-2">
        <p className="text-gray-600"><strong>Patient Name:</strong></p>
        <p className="text-gray-900">{patient.name}</p>
        
        <p className="text-gray-600"><strong>Patient ID:</strong></p>
        <p className="text-gray-900 font-mono text-xs">{patient._id}</p>
        
        <p className="text-gray-600"><strong>Health Card ID:</strong></p>
        <p className="text-gray-900 font-mono">{healthCard.cardID}</p>
        
        <p className="text-gray-600"><strong>Email:</strong></p>
        <p className="text-gray-900">{patient.email}</p>
      </div>
    </div>
  </div>
);

const PasswordDisplay = ({ password, onCopy, onPrint, copied }) => (
  <div className="mt-6 bg-yellow-50 p-6 rounded-lg border-2 border-yellow-400">
    <h4 className="font-bold text-yellow-900 mb-3 text-lg flex items-center justify-center">
      <svg className="w-6 h-6 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
      </svg>
      Temporary Password
    </h4>
    <div className="bg-white p-4 rounded border-2 border-yellow-300 mb-4">
      <p className="text-xs text-gray-600 mb-2">Password (provide this to the patient):</p>
      <p className="text-2xl font-mono font-bold text-center text-gray-900 tracking-wider select-all">
        {password}
      </p>
    </div>
    
    <div className="flex gap-3 justify-center mb-3">
      <button
        onClick={onCopy}
        className="flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors font-medium"
      >
        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
        </svg>
        {copied ? 'Copied! ✓' : 'Copy Password'}
      </button>
      
      <button
        onClick={onPrint}
        className="flex items-center gap-2 bg-gray-600 text-white px-4 py-2 rounded-lg hover:bg-gray-700 transition-colors font-medium"
      >
        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
        </svg>
        Print Credentials
      </button>
    </div>

    <div className="bg-red-50 border border-red-200 rounded p-3 mt-3">
      <p className="text-xs text-red-800 font-semibold">
        ⚠️ IMPORTANT: The patient must change this password upon first login for security reasons.
      </p>
    </div>
  </div>
);

const EmailConfirmation = () => (
  <div className="mt-6 bg-green-50 p-4 rounded-lg border border-green-200">
    <p className="text-sm text-green-800">
      ✅ Confirmation email with QR code and health card details has been sent to the patient.
    </p>
  </div>
);

export default RegistrationSuccess;
